### ISSUE TITLE
Query terminal background color

### ISSUE THREAD

**Issue by brandonkal** [termapps/enquirer#2]
The confirm prompt could be quite confusing to users who have for instance a Atom One Dark terminal theme. Because the background color is the same color as the " (y/N) ›" section it reads like so:
```
? Do you want to continue?     false |
```
The program should query the background color and ensure a suitable contrast ratio.

**Comment by pksunkara** [comment]
Unfortunately, I don't know what to do here. If you look at the code, https://github.com/termapps/enquirer/blob/master/src/theme.rs#L43

I am just doing `.black().bold()`.

**Comment by brandonkal** [comment]
Querying the terminal is probably too difficult.

The issue is that iTerm2 and probably other terminal emulators have "brighten bold text" checked by default. With these dark themes, ANSI black is often really close to the background color and bolding makes them the same.

I've found a third One Dark theme called "theOne" that darkens up the black color. So now this is useable for me but may not be usable for everyone. e.g. it is also an issue with "Solarized Dark" and "Bright Lights" themes.

One solution is to just use a different ansi color for the "y/N" string such as magenta, green, or yellow.

**Comment by pksunkara** [comment]
That is a good option. I will leave this issue open to see if anyone else is wanting the same. If they do, then I might change it.

**Comment by pksunkara** [comment]
@brandonkal I dug into this issue and looks like http://lib.rs/console doesn't support `bright`. `bold` is different than `bright`

`black` is `\x1B[30m`
`black.bold` is `\x1B[30m\x1B[1m`
`black.bright` is `\x1B[38;5;m`

I would love to add it, but I am bit busy with other stuff. Do you think you could add support for that to https://github.com/mitsuhiko/console?

**Comment by pksunkara** [comment]
This is now fixed.
