### ISSUE TITLE
Third choice

### ISSUE THREAD

**Issue by brandonkal** [termapps/enquirer#4]
Would it be possible to have a prompt like so:
```
Do you want to execute? (y/N/[p]review)
```
User could then hit y, enter, or n as normal but can also hit p to preview the action.

I am aware of the Select Prompt but it would be nice to have something compact.

**Comment by pksunkara** [comment]
So, basically [Select Prompt](https://github.com/termapps/enquirer#select-prompt) but in different style?

**Comment by brandonkal** [comment]
In the sense that it allows more than 2 choices, but the interface is closer to confirm.

**Comment by pksunkara** [comment]
Have you looked at the Select Prompt I linked above? I still don't get how it is different (other than the style of course).

**Comment by pksunkara** [comment]
I can add a compact style option for select prompt if you are agree.

**Comment by brandonkal** [comment]
Thank you but let's not.
Sorry, I should have opened this against dialoguer instead as it would need to be there first.

You can see I've added the feature as KeyPrompt in my dialoguer fork:
https://github.com/brandonkal/dialoguer
If you are curious you can clone and run `cargo run --example key` to see what I was going for.

It's a more generic solution to the problem above.

**Comment by pksunkara** [comment]
Looks like you wanted a separate prompt because of the difference in interaction. Now, I understand a bit more.
