### ISSUE TITLE
Animated svgs from the README aren't displayed properly

### ISSUE THREAD

**Issue by ngirard** [termapps/enquirer#6]
Using Firefox 82.0.3 on Ubuntu 20.04.
None of the animated svgs from the README are displayed properly.

See e.g.
![image](https://user-images.githubusercontent.com/98098/99877380-18a3af00-2bfe-11eb-9ba9-4989c618d1c6.png)

Cheers

**Comment by pksunkara** [comment]
I don't have an ubuntu to test this. Is this happening with firefox on other operating systems?

**Comment by ngirard** [comment]
> I don't have an ubuntu to test this. Is this happening with firefox on other operating systems?

I wouldn't tell, because I don't have any Windows box at my disposal right now ; but FWIW there's no such problem with Chromium 87.0.4280.66.

**Comment by ngirard** [comment]
Found other projects whose screencasts are problematic.

How did you create yours ?

**Comment by pksunkara** [comment]
I used https://github.com/marionebl/svg-term-cli

**Comment by pksunkara** [comment]
> In my Firefox, I got the "Minimum font size" setting set to 9. That's what's making the SVG looks like the screenshot. If I set "Minimum font size" to "None", then I get the expected result.

Or you can upgrade to firefox 78 since the bug got fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=935056
