### ISSUE TITLE
Unexpected behaviour when hitting Esc

### ISSUE THREAD

**Issue by ngirard** [termapps/enquirer#8]
Using Enquirer v0.5.0 (precompiled binary) on Ubuntu 20.04.

Steps to reproduce:
1. Type `enquirer multi-select -m "Choose" a b c d -s 1 2`
2. Hit `Esc`

Expected behaviour: no output is produced

Observed behaviour: the following lines are written to STDOUT:
```
a
b
```

**Comment by pksunkara** [comment]
That's intentional because by default you select 1,2 options. https://github.com/mitsuhiko/dialoguer

**Comment by ngirard** [comment]
I'm a bit surprised you decided to close this issue without any further discussion.

In UX selecting != choosing.
Selecting facilitates choosing by pre-populating dialog boxes with suggested values.
It's up to the user to either choose the suggested values, chose others, or not choose anything.

Take any "Open file" dialog box, say VSCode's. You'll see they come with selection, but don't force you to choose anything when you hit `Esc`.

**Comment by pksunkara** [comment]
Any behaviour issue would need to be created on the repo I linked above since this tool is just a wrapper around it.

**Comment by ngirard** [comment]
@pksunkara, it is your tool I evaluated and found to misbehave, in my humble opinion, and I gave you my reason.
Do we agree on this misbehaviour ?

If so, I think this issue should stay open until the problem is solved.
If not, would you mind explaining why ?

Then, if we agree that there is a problem, and the problem comes from Dialoguer, are you willing to report it upstream ? If not, I'm willing to do so.

Cheers

**Comment by ngirard** [comment]
> @pksunkara, it is your tool I evaluated and found to misbehave, in my humble opinion, and I gave you my reason.
> Do we agree on this misbehaviour ?
> 
> If so, I think this issue should stay open until the problem is solved.
> If not, would you mind explaining why ?
> 
> Then, if we agree that there is a problem, and the problem comes from Dialoguer, are you willing to report it upstream ? If not, I'm willing to do so.
> 

An answer would be appreciated !
Cheers
