### ISSUE TITLE
multi-select: return value doesn't reflect user behaviour

### ISSUE THREAD

**Issue by ngirard** [termapps/enquirer#9]
Using Enquirer v0.5.0 (precompiled binary) on Ubuntu 20.04.

The return value of `enquirer` is always 0, no matter the user's decision.

This worsens the behaviour already described in #8 and prevents any script from knowing whether the user has chosen anything or not.

To illustrate this issue, I'll compare Enquirer's current behaviour with a popular, similar-scoped tool: [Rofi](https://github.com/davatorium/rofi).

The following invocation produces a modal dialog, allowing the user to choose between "foo" and "bar", with the "bar" option selected:
```sh
echo -e "foo\nbar\n" | rofi -dmenu -multi-select bar
```
From there:
* if the user hits `Enter`: "bar" is written to STDOUT, and the return value is 0;
* if the user hits `Esc`: nothing is written to STDOUT, and the return value is 1.

The equivalent Enquirer invocation is
```sh
enquirer multi-select -m Choose foo bar -s 2
```

From there:
* if the user hits `Enter`: "bar" is written to STDOUT, and the return value is 0 (as expected);
* if the user hits `Esc`: "bar" is also written to STDOUT, and the return value is also 0

The expected behaviour is Rofi's one: that when the user hits `Esc`, nothing gets written to STDOUT, and another return value than 0 is given.

The comparison given also serves as an illustration for the problem already reported in #8.

**Comment by Animeshz** [comment]
Problem is that enquirer is not rofi, to put another way, if you are working for something like a package manager you wouldn't want to exit on `esc/q`, unless user sends SIGTERM, so default behavior shouldn't be allow to exit on such keys.

But an external cancel option can be provided for working with such situations where cancellation can be made, which will need same changes on the upstream (dialoguer).

**Comment by Animeshz** [comment]
Should be superseded by https://github.com/mitsuhiko/dialoguer/pull/136, will only require an optional `-c|--cancel` option in all the select/sorting variant (except input and secret) to be added, and usage of `interact_opt -> Result<Option<T>>` instead of `interact -> Result<T>` in it, the former will allow exiting and the latter will ignore the `Esc|q` sequences and wait until `Enter`.
